services:
  postgres:
    image: postgres:latest
    container_name: chat_db
    restart: always
    environment:
      POSTGRES_USER: user_root
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data:
